### ISSUE TITLE
.mra files missing for Super Hang-On core

### ISSUE THREAD

**Issue by Klezstyle** [jotego/jtcores_mister#3]
Hi Jotego,

It seems that in this "jtcores_mister" repo you included the Super Hang-On core 'jtshanon_20221104.rbf' but not the related .mra files. 

Like:

- Super Hang-On (sitdown-upright) (unprotected).mra
- Limited Edition Hang-On.mra
- Super Hang-On (mini ride-on) (FD1089B 317-0034).mra
- Super Hang-On (mini ride-on, Rev A) (FD1089B 317-0034).mra
- Super Hang-On (sitdown-upright) (FD1089B 317-0034).mra

Feliz navidad

**Comment by jotego** [comment]
That is an automatically generated repository. MRA for games in beta are not listed there. I was meant to make Super Hang On public last month but got busy with other stuff. I'll change it to public when I have a chance to review it. 

Thanks for reporting it, but it's fine.
