### ISSUE TITLE
Street Fighter Zero 2 Alpha (Japan 960805)

### ISSUE THREAD

**Issue by francoisrrr** [jotego/jtcores_mister#9]
Not sure if it’s a glitch or not since I don’t have the original CPS2 game. When you finish a game and enter your name, you’re greeted  with the « score ranking screen ». Icons are surrounded by 2 blocks in solid blue color (cf. attached screenshot).

![IMG_0895](https://user-images.githubusercontent.com/49022882/233058451-910fd9ba-71b9-4169-98ed-7bae0df1c794.jpeg)

**Comment by theypsilon** [comment]
Please report it in jtbin
